//! Canonical product vocabulary shared by every UI renderer.
//! See `docs/glossary.md` for meanings, compatibility names, and usage rules.

/// A product term or action. Contextual prose may explain its effect further.
pub struct Entry {
    pub name: &'static str,
    pub definition: &'static str,
}

macro_rules! glossary {
    ($($id:ident => ($name:literal, $definition:literal),)*) => {
        $(pub const $id: &str = $name;)*
        pub const ENTRIES: &[Entry] = &[
            $(Entry { name: $name, definition: $definition },)*
        ];
    };
}

glossary! {
    OBJECTS => ("Objects", "A workflow pass for focused annotation or review of one object at a time."),
    OVERVIEW => ("Overview", "A workflow pass for checking the complete image and handling missing objects after its Objects work is finished."),
    PREVIOUS => ("Previous", "Return to the previous item in this workflow's saved history."),
    BOOSTED_WORKFLOW => ("Boosted workflow", "A workflow whose annotations currently earn a scoring bonus."),
    DATASET => ("Dataset", "Images, workflow configuration, annotations, and their history managed together."),
    WORKFLOW => ("Workflow", "A configured labeling process for one annotation type and class. Stored as a task in the API and dataset configuration."),
    ASSIGNMENT => ("Assignment", "Work claimed by one person for an image and workflow."),
    ANNOTATION => ("Annotation", "A saved or draft bounding box or skeleton describing an object."),
    OBJECT => ("Object", "An entity in an image, which may have related bounding-box and skeleton annotations or a pending prelabel."),
    PRELABEL => ("Prelabel", "A model-generated suggestion awaiting human confirmation; it is not yet a saved annotation."),
    GUIDE => ("Guide", "Read-only source geometry used to place or check an annotation during migration or companion annotation."),
    CLASS => ("Class", "The configured category of an object."),
    BOUNDING_BOX => ("Bounding box", "A rectangular annotation around an object."),
    SKELETON => ("Skeleton", "An annotation containing named keypoints and their visibility states."),
    KEYPOINT => ("Keypoint", "A named location in a skeleton."),
    VISIBLE => ("Visible", "A keypoint positioned at a directly visible location."),
    OCCLUDED => ("Occluded", "A keypoint with a position inferred despite visual obstruction."),
    NOT_PRESENT => ("Not present", "An allowed optional keypoint recorded without a position."),
    REVIEW => ("Review", "Checking submitted annotations and recording approval, rejection, or corrections."),
    CORRECTION => ("Correction", "An edit made to address an annotation problem."),
    MIGRATION => ("Migration", "Guided creation of skeleton annotations from existing bounding-box guides."),
    BOUNDING_BOX_ANNOTATION => ("Bounding box annotation", "Create or edit bounding boxes for the selected class."),
    BOUNDING_BOX_REVIEW => ("Bounding box review", "Review submitted bounding boxes for the selected class."),
    SKELETON_REVIEW => ("Skeleton review", "Review submitted skeletons for the selected class, including migrated skeletons."),
    SKELETON_ANNOTATION => ("Skeleton annotation", "Create or edit skeletons directly for the selected class."),
    ADD_MISSING_OBJECTS => ("Add missing objects", "Begin a skeleton for an object without a bounding-box guide during migration full-image confirmation."),
    BOXES => ("Boxes", "Compact class activity label for bounding box annotation."),
    MIGRATE => ("Migrate", "Compact class activity label for migration."),
    MISSING_OBJECTS => ("Missing", "Compact class activity label for adding missing objects."),
    FULL_IMAGE => ("Full image", "The complete image, including objects outside the currently focused guide."),
    PENDING => ("Pending", "A workflow on an image that has not started."),
    IN_PROGRESS => ("In progress", "A workflow on an image with work underway."),
    AWAITING_REVIEW => ("Awaiting review", "Submitted work waiting for a reviewer."),
    NEEDS_CORRECTION => ("Needs correction", "Work returned for annotation changes."),
    COMPLETED => ("Completed", "A workflow on an image that has met its completion requirements."),
    EXCLUDED => ("Excluded", "An item deliberately omitted with a recorded reason."),
    APPROVED => ("Approved", "A positive review decision. A review outcome is distinct from workflow completion state."),
    REJECTED => ("Rejected", "A negative review decision requiring changes."),
    DRAFT => ("Draft", "Local or staged changes that have not been committed by the relevant save or submit action."),
    SAVED => ("Saved", "Changes successfully committed by a save operation."),
    SAVING => ("Saving", "A save operation is pending."),
    UNSAVED_CHANGES => ("Unsaved changes", "Edits that have not yet been saved."),
    CANVAS => ("Canvas", "The image area used for viewing and editing geometry."),
    WORKSPACE => ("Workspace", "The image, workflow controls, canvas, and associated panels."),
    INSPECTOR => ("Inspector", "The panel containing details and controls for the current object."),
    INSPECT => ("Inspect", "Open read-only dataset image inspection."),
    IMAGES => ("Images", "The dataset image collection or its navigation panel."),
    OVERLAYS => ("Overlays", "Annotation geometry displayed over an image during inspection."),
    ANNOTATE => ("Annotate", "Open the annotation workspace to create or edit annotations."),
    ADMIN => ("Admin", "Dataset configuration and management controls."),
    SETUP => ("Setup", "Dataset selection, creation, and application setup."),
    SETTINGS => ("Settings", "Personal application preferences and shortcut configuration."),
    STATISTICS => ("Statistics", "Workflow progress and contributor activity."),
    ABOUT => ("About", "Application and server build information."),
    TUTORIAL => ("Tutorial", "Instructions for the selected workflow."),
    SCHEMA => ("Schema", "Reusable class, workflow, and skeleton definitions."),
    SNAPSHOTS => ("Snapshots", "Captured dataset metadata and history; image bytes and authentication state are not included and native restore is unavailable."),
    SNAPSHOT => ("Snapshot", "One captured set of dataset metadata and history."),
    IMPORT => ("Import", "Create a new dataset from a supported ground-truth source."),
    EXPORT => ("Export", "Capture and deliver supported detection or pose data from a dataset."),
    INGESTION => ("Ingestion", "Discover image files in configured roots and update the image index."),
    PREFLIGHT => ("Preflight", "Validate a proposed import or export before starting publication or capture."),
    MODEL => ("Model", "A configured inference model used to generate prelabels."),
    ROLES => ("Roles", "Permissions assigned to people within a dataset."),
    ANNOTATOR => ("Annotator", "A person permitted to claim and annotate work."),
    REVIEWER => ("Reviewer", "A person permitted to review submitted annotations."),
    DATA_ADMIN => ("Data admin", "A person permitted to manage dataset configuration and data."),
    PEOPLE => ("People", "Dataset members and role management."),
    LEADERBOARD => ("Leaderboard", "Contributor ranking for the selected activity period."),
    STREAK => ("Streak", "Consecutive qualifying days of annotation activity."),
    SCORE => ("Score", "Contribution points computed by the scoring policy."),
    SPLIT => ("Split", "A dataset partition such as train, validation, or test."),
    SOURCE => ("Source", "The input selected for import or configuration reuse."),
    STATUS => ("Status", "The current state of an item or operation."),
    SAVE => ("Save", "Commit current edits without submitting the image or advancing to another assignment."),
    SUBMIT => ("Submit", "Complete and submit the current image workflow when its requirements are satisfied."),
    SUBMIT_NEXT => ("Submit & next", "Finish the current item and advance within this workflow's queue."),
    CONFIRM_NEXT => ("Confirm & next", "Confirm the current prelabel geometry or deletion, then advance to the next object."),
    NEXT_OBJECT => ("Next object", "Move to the next object in the current image; the workflow determines whether confirmation is required first."),
    PREVIOUS_OBJECT => ("Previous object", "Historical object-navigation label; item queues use Previous across image boundaries."),
    NEXT_GUIDE => ("Next guide", "Save the current companion annotation and advance within Objects; Overview is completed separately."),
    PREVIOUS_IMAGE => ("Previous image", "Historical image-navigation label; item queues use configurable Previous history."),
    NEXT_IMAGE => ("Next image", "Navigate to the next image in dataset inspection."),
    APPROVE => ("Approve", "Confirm an acceptable review item or submit final image approval, according to the review phase."),
    SUBMIT_CORRECTION => ("Submit correction", "Confirm the current correction or submit accumulated corrections, according to the review phase."),
    APPROVE_DIRECTLY => ("Approve directly", "Shortcut-only direct approval of the current review target."),
    REJECT_DIRECTLY => ("Reject directly", "Shortcut-only rejection through the review correction and rejection flow."),
    REJECT => ("Reject", "Record a negative review decision."),
    CONFIRM_SUBMIT => ("Confirm / submit", "The context-dependent primary-work shortcut; each concrete operation retains its own glossary entry."),
    SAVE_SKELETON_ADVANCE => ("Save skeleton & advance", "Save the skeleton for the current migration guide and advance."),
    SAVE_NEXT => ("Save & next", "Compact form of Save skeleton & advance."),
    SAVE_MISSING_OBJECT => ("Save missing object", "Save a skeleton for a newly discovered object during migration."),
    SAVE_OBJECT => ("Save object", "Compact form of Save missing object."),
    SAVE_OBJECT_CHANGES => ("Save object changes", "Save edits to a previously added migration object."),
    SAVE_CHANGES => ("Save changes", "Commit staged edits; also the compact form of Save object changes in migration."),
    KEEP_CURRENT_ADVANCE => ("Keep current & advance", "Keep the current migration disposition and advance to the next guide."),
    KEEP_NEXT => ("Keep & next", "Compact form of Keep current & advance."),
    CONFIRM_ALL_GUIDES_FINISH => ("Confirm all guides & finish", "Confirm the migration full-image scan after all guides are resolved."),
    CONFIRM_NO_GUIDES_FINISH => ("Confirm no guides & finish", "Confirm that the image has no migration guides and needs no skeletons."),
    CONFIRM_FINISH => ("Confirm & finish", "Compact form of the applicable migration full-image confirmation."),
    SKIP => ("Skip", "Save partial work, release this item, and request another item in this workflow."),
    UNDO => ("Undo", "Reverse the last supported annotation edit."),
    UNDO_LAST_KEYPOINT => ("Undo last keypoint", "Remove the last draft keypoint during migration."),
    REDO => ("Redo", "Reapply the last undone annotation edit where supported."),
    DELETE => ("Delete", "Remove the selected annotation, pending prelabel, or editable migration addition according to context."),
    DISCARD_CHANGES => ("Discard changes", "Abandon staged edits without saving them."),
    CANCEL => ("Cancel", "Cancel the current interaction or pending operation where cancellation is supported."),
    CLOSE => ("Close", "Dismiss the current view or overlay."),
    RETRY => ("Retry", "Repeat a failed operation while preserving its applicable retry identity."),
    REFRESH => ("Refresh", "Reload the current region from the server."),
    RESET => ("Reset", "Restore the relevant setting or item to its defined baseline."),
    PAN => ("Pan", "Move the visible image region without editing annotations."),
    FIT => ("Fit", "Fit and center the complete image in the canvas."),
    REFOCUS => ("Refocus", "Center and zoom the canvas to the active object or guide."),
    ZOOM_IN => ("Zoom in", "Increase canvas magnification."),
    ZOOM_OUT => ("Zoom out", "Decrease canvas magnification."),
    RETURN_TO_REVIEW => ("Return to review", "Reopen eligible completed workflows for a new review."),
    SIGN_IN => ("Sign in", "Authenticate to access Labello."),
    SIGN_OUT => ("Sign out", "End the current authenticated session."),
    SEARCH => ("Search", "Filter the displayed entries by the entered query."),
    NAME => ("Name", "A human-readable name, including names supplied by dataset administrators."),
    WORKFLOW_ID => ("Workflow ID", "The stable identifier of a workflow; serialized as a task identifier."),
    PER_WORKFLOW => ("Per workflow", "Progress grouped by configured workflow."),
    WORKFLOW_PANEL => ("Workflow panel", "The panel for selecting the active workflow."),
    INSPECTOR_PANEL => ("Inspector panel", "The panel for object details and controls."),
    PREVIOUS_WORKFLOW => ("Previous workflow", "Select the previous enabled workflow."),
    NEXT_WORKFLOW => ("Next workflow", "Select the next enabled workflow."),
    PREVIOUS_PRELABEL => ("Previous prelabel", "Select the previous model-generated suggestion."),
    NEXT_PRELABEL => ("Next prelabel", "Select the next model-generated suggestion."),
    CONFIRM_SELECTED_PRELABEL => ("Confirm selected prelabel", "Confirm the selected prelabel with its edits and advance."),
    DELETE_SELECTED_PRELABEL => ("Delete selected prelabel", "Delete the selected pending prelabel; pending bounding-box deletion still requires confirmation."),
    VISIBLE_OCCLUDED => ("Visible / Occluded", "Toggle the keypoint visibility state for editing or placement."),
    ADD_OR_CANCEL_MISSING_MIGRATION_OBJECT => ("Add or cancel missing migration object", "Begin or cancel a skeleton for an object absent from imported data."),
    RETRY_IMAGE_LOAD => ("Retry image load", "Try again to claim and load an image."),
    BOUNDING_BOX_TOOL => ("Bounding-box tool", "Legacy annotation tool binding retained for compatibility, not an active configurable action."),
    KEYPOINT_TOOL => ("Keypoint tool", "Legacy annotation tool binding retained for compatibility, not an active configurable action."),
    OFFLINE_MODE => ("Offline mode", "Legacy binding; browser offline annotation is not an operational workflow."),
    RETAINED_PRELABELS => ("Retained prelabels", "Model predictions cached for reuse, bound to the image, workflow, model, and reset generation."),
    DATASET_PRELABELS => ("Dataset prelabels", "Dataset-wide generation and management of retained prelabels."),
    REFRESH_PRELABELS => ("Refresh prelabels", "Reload or regenerate the current eligible prelabels."),
    REMOVE_PRELABELS_AND_PAUSE => ("Remove prelabels and pause", "Remove retained prelabels in the selected scope and pause generation; preserve annotations and drafts."),
    RESUME_PRELABELS_IN_THIS_SCOPE => ("Resume prelabels in this scope", "Allow prelabel generation again within the selected administrative scope."),
    RESET_ITEM => ("Reset item", "Reset the editable review item according to its current correction state."),
    CREATE => ("Create", "Create the specified dataset, class, workflow, or configuration item."),
    DOWNLOAD => ("Download", "Transfer the selected available artifact to the browser."),
    RELOAD => ("Reload", "Fetch current server state again, with the applicable draft-discard guard."),
    REOPEN => ("Reopen", "Make a resolved item editable again where the workflow permits it."),
    REMOVE => ("Remove", "Remove the specified configuration or retained artifact after its applicable confirmation."),
    CONFIRM => ("Confirm", "Commit the stated decision; its object and effect must be explicit in context."),
    ENABLED => ("Enabled", "Available for use under the item's configuration and access rules."),
    DISABLED => ("Disabled", "Not available for use under the item's configuration or current state."),
    AUTOMATION => ("Automation", "Administration of inference models and dataset prelabel generation."),
    EXCLUSION => ("Exclusion", "A recorded reason for omitting an item from annotation or migration coverage."),
    CONFIDENCE => ("Confidence", "The model score for a predicted object."),
    THRESHOLD => ("Threshold", "The cutoff applied to the named model score or overlap measure."),
    IMAGE => ("Image", "One source image in a dataset, identified independently of its filename."),
    KEYBINDINGS => ("Keybindings", "Saved mappings from configurable actions to input shortcuts."),
}

pub(crate) mod shortcuts;

#[cfg(test)]
mod tests;

/// Canonical annotation type name for selectors and configuration summaries.
pub(crate) fn annotation_type_name(kind: &labello_domain::AnnotationType) -> &'static str {
    match kind {
        labello_domain::AnnotationType::BoundingBox => BOUNDING_BOX,
        labello_domain::AnnotationType::Skeleton => SKELETON,
    }
}
